apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: scala-fun-backend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        service: scala-fun-backend
    spec:
      containers:
      - name: scala-fun-backend
        image: spikerlabs/scala-fun-backend:%%VERSION%%
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /next
            port: 8080
        env:
          - name: POCKET_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                name: scala-fun
                key: pocket-access-token
          - name: POCKET_CONSUMER_KEY
            valueFrom:
              secretKeyRef:
                name: scala-fun
                key: pocket-consumer-key
          - name: EVENTSTORE_HOST
            value: scala-fun-eventstore
